# Generated by Django 4.0.4 on 2022-05-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_delete_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
