# Generated by Django 4.0.4 on 2022-05-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to=None,
        ),
    ]
